# TCL File Generated by Component Editor 18.1
# Fri Dec 17 17:04:43 CET 2021
# DO NOT MODIFY


# 
# CameraController "CameraController" v1.0
#  2021.12.17.17:04:43
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module CameraController
# 
set_module_property DESCRIPTION ""
set_module_property NAME CameraController
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CameraController
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Camera_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Camera_controller.vhd VHDL PATH ../hdl/Camera_controller.vhd TOP_LEVEL_FILE
add_fileset_file AS_sub.vhd VHDL PATH ../hdl/AS_sub.vhd
add_fileset_file Camera_interface_sub.vhd VHDL PATH ../hdl/Camera_interface_sub.vhd
add_fileset_file DMA_sub.vhd VHDL PATH ../hdl/DMA_sub.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AM_Address address Output 32
add_interface_port avalon_master AM_DataWr writedata Output 32
add_interface_port avalon_master AM_WaitRequest waitrequest Input 1
add_interface_port avalon_master AM_Write write Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender AM_irq irq Output 1


# 
# connection point Camera
# 
add_interface Camera conduit end
set_interface_property Camera associatedClock ""
set_interface_property Camera associatedReset ""
set_interface_property Camera ENABLED true
set_interface_property Camera EXPORT_OF ""
set_interface_property Camera PORT_NAME_MAP ""
set_interface_property Camera CMSIS_SVD_VARIABLES ""
set_interface_property Camera SVD_ADDRESS_GROUP ""

add_interface_port Camera C_FVAL frame_valid Input 1
add_interface_port Camera C_LVAL line_valid Input 1
add_interface_port Camera C_data data Input 12


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AS_Wr write Input 1
add_interface_port avalon_slave AS_DataWr writedata Input 32
add_interface_port avalon_slave AS_Address address Input 2
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pixclk
# 
add_interface pixclk clock end
set_interface_property pixclk clockRate 0
set_interface_property pixclk ENABLED true
set_interface_property pixclk EXPORT_OF ""
set_interface_property pixclk PORT_NAME_MAP ""
set_interface_property pixclk CMSIS_SVD_VARIABLES ""
set_interface_property pixclk SVD_ADDRESS_GROUP ""

add_interface_port pixclk C_pixclk clk Input 1


# 
# connection point CameraClk
# 
add_interface CameraClk clock start
set_interface_property CameraClk associatedDirectClock ""
set_interface_property CameraClk clockRate 0
set_interface_property CameraClk clockRateKnown false
set_interface_property CameraClk ENABLED true
set_interface_property CameraClk EXPORT_OF ""
set_interface_property CameraClk PORT_NAME_MAP ""
set_interface_property CameraClk CMSIS_SVD_VARIABLES ""
set_interface_property CameraClk SVD_ADDRESS_GROUP ""

add_interface_port CameraClk CameraClk clk Output 1


# 
# connection point CameraReset_n
# 
add_interface CameraReset_n reset start
set_interface_property CameraReset_n associatedClock clock
set_interface_property CameraReset_n associatedDirectReset ""
set_interface_property CameraReset_n associatedResetSinks ""
set_interface_property CameraReset_n synchronousEdges DEASSERT
set_interface_property CameraReset_n ENABLED true
set_interface_property CameraReset_n EXPORT_OF ""
set_interface_property CameraReset_n PORT_NAME_MAP ""
set_interface_property CameraReset_n CMSIS_SVD_VARIABLES ""
set_interface_property CameraReset_n SVD_ADDRESS_GROUP ""

add_interface_port CameraReset_n CameraReset_n reset_n Output 1

